version: '3'
services:
  postgres:
    image: postgres:latest
    environment: 
        POSTGRES_USER: root
        POSTGRES_PASSWORD: P@ssw0rd
        POSTGRESS_DB: streaming_db
    ports:
      - "5432:5432"

  jupyter:
    image: jupyter/base-notebook
    ports:
      - "8888:8888"
    volumnes:
      - ./notebooks:/home/patcharapon/work